### PR TITLE
pkg/core/session.go: add WithMaxComPacketSize ControlSessionOpt

### PR DESCRIPTION
**Pull request by yogev-lb**
minor(session): add option params to set MaxComPacketSize
    
    some SEDs are apparently unable to handle some Properties() Session
    Manager method request arguments gracefully if they exceed the values
    supported by the TPer.
    
    e.g., as of FW version E2MU110, if Micron 7450 family devices are passed
    HostProperties.MaxComPacketSize of >128kB (and possibly the related
    Max*PacketSize values) on Properties() invocation, the subsequent
    IF-RECV calls might sporadically fail with EINVAL (22) error.
    
    the recommended vendor workaround is to always pass in a value <= 128kB
    to HostProperties.MaxComPacketSize, regardless of host capabilities.
    
    this patch adds option params to core.NewControlSession() and
    locking.Initialize() allowing to override the MaxComPacketSize value.
    
    issue: LBM1-20784

### CODE REVIEW

**Comment by yogev-lb** [comment]
@lev-lb ping

**Comment by lev-lb** [comment]
@ChriMarMe : as a follow-up to our [last exchange](https://github.com/LightBitsLabs/go-tcg-storage/pull/1#discussion_r901387979), please see if this works for you.

**Comment by ChriMarMe** [comment]
LGTM

**Comment by lev-lb** [comment]
@ChriMarMe : thanks. how would we go about having it merged into [go-tcg-storage](https://github.com/open-source-firmware/go-tcg-storage) proper?

**Comment by lev-lb** [comment]
@ChriMarMe : no paperwork?

**Comment by yogev-lb** [comment]
issued PR against upstream: https://github.com/open-source-firmware/go-tcg-storage/pull/95

**Pull request closed without merging**
